---
apiVersion: v1
kind: Service
metadata:
  name: drupal
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: drupal
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: drupal
spec:
  selector:
    matchLabels:
      app: drupal
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: drupal
    spec:
      containers:
      - image: drupal:9
        name: drupal
        env:
          - name: DRUPAL_DB_HOST
            value: wordpress-mysql
          - name: DRUPAL_DB_USER
            value: wordpress
          - name: DRUPAL_DB_PASSWORD
            value: password
          - name: DRUPAL_DB_NAME
            value: wordpress
        ports:
        - containerPort: 80
          name: drupal
        volumeMounts:
        - name: drupal-persistent-storage
          mountPath: /var/www/html/sites/default/files
      volumes:
      - name: drupal-persistent-storage
        persistentVolumeClaim:
          claimName: drupal-pv-claim
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: drupal-pv-volume
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0b72cd50df7bd8da0
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: drupal-pv-claim
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 5Gi
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: efs-sc
provisioner: efs.csi.aws.com
volumeBindingMode: Immediate